[platformio]
src_dir = main
[env:esp32s3]
platform = espressif32
board = lxb-esp32-s3-n16r8
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
monitor_port = COM8
monitor_filters = esp32_exception_decoder
build_type = release
